AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable
  SuggestExtensions: false

Style/ClassVars:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Naming/FileName:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Lint/DuplicateBranch:
  Enabled: false

Metrics/BlockLength:
  Enabled: true
  Exclude:
  - 'spec/**/*'

Metrics/ClassLength:
  Enabled: true
  Exclude:
  - 'spec/**/*'

Style/FrozenStringLiteralComment:
  Enabled: true
  Exclude:
  - 'exe/*'
